---
title: TIL 190719 - async/await
date: '2019-07-19T10:46:37.121Z'
template: 'post'
draft: true
slug: 'til/190719'
category: 'TIL'
tags:
  - 'TIL'
  - 'Log'
description: 'async/await 에 대해 공부했다'
---

## 어떻게 생겨먹었나? 

- 아래와 같은 모습을 하고 있다.

```js
async function f() {

  let promise = new Promise((resolve, reject) => {
    setTimeout(() => resolve("done!"), 1000)
  });

  let result = await promise; // promise 가 resolves 될 때 까지 기다린다. (*)

  alert(result); // 다 되면 result에 할당이 일어나고 뒤 이은 코드가 동기적으로 실행된다.
}

f();
```

## 왜 태어났니?

- .then 체이닝이 복잡해서
- 비동기 코드이지만 인간의 눈에 동기적으로 보이게 만들면 인지하기 편하니까
- 에러처리도 동기처럼 try/catch 처럼 쓸 수 있어서 일관성이 생기니까

## 특징

### await 는 non-promise 값이 와도 resolved promise로 바꿔줌

```js
async function f() {
  return 1;
}

f().then(alert); // 1
```

- 위 코드는 사실 아래와 같음

```js
sync function f() {
  return Promise.resolve(1);
}

f().then(alert); // 1
```



## await 는 thenable 한 객체 인스턴스를 받을 수 있음 

- 해당 인스턴스가 then method를 가지고 있으면 await를 사용할 수 있다는 말임
- 이것이 바로 [duck typing(오리처럼 생겼으면 오리라고 생각하자)](https://devopedia.org/duck-typing)

```javascript
class Thenable {
  constructor(num) {
    this.num = num;
  }
  then(resolve, reject) {
    alert(resolve);
    // resolve with this.num*2 after 1000ms
    setTimeout(() => resolve(this.num * 2), 1000); // (*)
  }
};

async function f() {
  // waits for 1 second, then result becomes 2
  let result = await new Thenable(1);
  alert(result);
}

f();
```

## [Rewrite "rethrow" with async/await](https://javascript.info/async-await#rewrite-rethrow-with-async-await)

### Promise 버전

```js
class HttpError extends Error {
  constructor(response) {
    super(`${response.status} for ${response.url}`);
    this.name = 'HttpError';
    this.response = response;
  }
}

function loadJson(url) {
  return fetch(url)
    .then(response => {
      if (response.status == 200) {
        return response.json();
      } else {
        throw new HttpError(response);
      }
    })
}

// Ask for a user name until github returns a valid user
function demoGithubUser() {
  let name = prompt("Enter a name?", "iliakan");

  return loadJson(`https://api.github.com/users/${name}`)
    .then(user => {
      alert(`Full name: ${user.name}.`);
      return user;
    })
    .catch(err => {
      if (err instanceof HttpError && err.response.status == 404) {
        alert("No such user, please reenter.");
        return demoGithubUser();
      } else {
        throw err;
      }
    });
}

demoGithubUser();
```

### Async/Await 버전

```javascript
class HttpError extends Error {
  constructor(response) {
    super(`${response.status} for ${response.url}`);
    this.name = 'HttpError';
    this.response = response;
  }
}

async function loadJson(url) {
  let response = await fetch(url);
  if (response.status == 200) {
    return response.json();
  } else {
    throw new HttpError(response);
  }
}

// Ask for a user name until github returns a valid user
async function demoGithubUser() {

  let user;
  while(true) {
    let name = prompt("Enter a name?", "iliakan");

    try {
      user = await loadJson(`https://api.github.com/users/${name}`);
      break; // no error, exit loop
    } catch(err) {
      if (err instanceof HttpError && err.response.status == 404) {
        // loop continues after the alert
        alert("No such user, please reenter.");
      } else {
        // unknown error, rethrow
        throw err;
      }
    }
  }


  alert(`Full name: ${user.name}.`);
  return user;
}

demoGithubUser();
```

>  ## 참고
>
> - https://javascript.info/async-await#rewrite-rethrow-with-async-await